"""add total_price to order

Revision ID: 251fd05495d6
Revises: 6761971a236d
Create Date: 2026-05-19 01:32:11.242753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251fd05495d6'
down_revision = '6761971a236d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###
