"""add relations cart order product

Revision ID: 6761971a236d
Revises: c1dbe68e4159
Create Date: 2026-05-18 16:39:38.386946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6761971a236d'
down_revision = 'c1dbe68e4159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
