"""fix payment relation

Revision ID: 7e3b3c251bd4
Revises: 8da59159b228
Create Date: 2026-05-20 11:25:32.961570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3b3c251bd4'
down_revision = '8da59159b228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
