"""add created_at to category

Revision ID: 8e3bb079889d
Revises: ff853cdedf6d
Create Date: 2026-05-18 13:12:47.523528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3bb079889d'
down_revision = 'ff853cdedf6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
