"""add shipping address to orders

Revision ID: 9ee887e9d6f0
Revises: bda36ddd887a
Create Date: 2026-05-20 23:16:55.127147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee887e9d6f0'
down_revision = 'bda36ddd887a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_full_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_full_name')
    # ### end Alembic commands ###
