"""add price to cart item

Revision ID: cfab30212fc1
Revises: 9ee887e9d6f0
Create Date: 2026-05-21 11:43:21.805634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfab30212fc1'
down_revision = '9ee887e9d6f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'cart_items',
    sa.Column(
        'price',
        sa.Float(),
        nullable=False,
        server_default="0"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'price')
    # ### end Alembic commands ###
